import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { createHash } from 'node:crypto';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { loadConfig } from '../src/config.js';
import { openStore } from '../src/store.js';
import { createApp } from '../src/app.js';
const ORIGIN = 'http://localhost:8000';
const IDS = { A:'111111111111111111', B:'222222222222222222', ADMIN:'333333333333333333' };
const challenge = v => createHash('sha256').update(v).digest('base64url');
const submission = (overrides={}) => ({name:'Development Fixture · Example',description:'Test data, not a real community endorsement.',author:'Fixture Author',sourceType:'github',sourceUrl:'https://github.com/example/fixture',tags:['test'],...overrides});
async function fixture(t, options={}) {
  const config = loadConfig({ DISCORD_CLIENT_ID:'000000000000000001',DISCORD_CLIENT_SECRET:'test-only-discord-secret',SESSION_SECRET:'test-only-session-secret-xxxxxxxxxxxxxxxxxxxxxxxx',MIEMIE_ADMIN_DISCORD_IDS:IDS.ADMIN, ...options.env });
  let clock=Date.now(); const store = openStore(options.path||':memory:');
  const profiles = Object.fromEntries(Object.entries(IDS).map(([key,id])=>[key,{id,displayName:`Development Fixture ${key}`,username:`fixture_${key}`,avatarBytes:null}]));
  const inspections=[];
  const github = { async inspect(url) { inspections.push(url); if(options.beforeInspect) await options.beforeInspect(url); const u=new URL(url), [,owner,repo]=u.pathname.split('/'); if(repo==='missing') {const error=new Error('not public'); error.status=400;throw error;} return {owner,repo,compatibility:'external',manifest:null,release:null,reason:'fixture metadata'}; } };
  const app=createApp({config,store,now:()=>clock,rateLimit:options.rateLimit||10000,github,discord:{authorizationUrl:state=>`https://discord.com/oauth2/authorize?state=${state}`,async exchange(code){if(!profiles[code])throw new Error('invalid OAuth code');return profiles[code];}}});
  const server=createServer(app.handler); await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve)); const base=`http://127.0.0.1:${server.address().port}`;
  t.after(async()=>{await new Promise(resolve=>server.close(resolve));app.close();store.close();});
  async function req(path, {method='GET',body,token,origin=ORIGIN,headers={}}={}) {
    const response=await fetch(`${base}${path}`,{method,headers:{...(origin?{Origin:origin}:{}),...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`} : {}),...headers},body:body?JSON.stringify(body):undefined,redirect:'manual'});
    const raw=await response.text();let data;try{data=JSON.parse(raw);}catch{data=raw;} return {status:response.status,data,headers:response.headers};
  }
  async function begin(verifier='v'.repeat(43)) {const start=await req('/api/auth/start',{method:'POST',body:{codeChallenge:challenge(verifier),returnOrigin:ORIGIN}});assert.equal(start.status,200);const auth=await req(new URL(start.data.authorizationUrl).pathname+new URL(start.data.authorizationUrl).search,{origin:null});assert.equal(auth.status,302);return {requestId:start.data.requestId,verifier,cookie:auth.headers.get('set-cookie').split(';')[0],state:new URL(auth.headers.get('location')).searchParams.get('state')};}
  async function callback(flow, who='A', overrides={}) {return req(`/api/auth/callback?state=${encodeURIComponent(flow.state)}&code=${who}`,{origin:null,headers:{Cookie:flow.cookie},...overrides});}
  async function login(who='A') {const flow=await begin();const cb=await callback(flow,who);assert.equal(cb.status,200);const bridge=JSON.parse(cb.data.match(/postMessage\((\{.*?\}),/)[1]);const exchanged=await req('/api/auth/exchange',{method:'POST',body:{code:bridge.code,requestId:flow.requestId,codeVerifier:flow.verifier}});assert.equal(exchanged.status,200);return {...exchanged.data,flow,bridge};}
  return {config,store,req,begin,callback,login,profiles,inspections,advance:n=>clock+=n};
}

test('public catalog works with no OAuth configuration; unauthenticated posting rejected',async t=>{const f=await fixture(t,{env:{DISCORD_CLIENT_ID:'',DISCORD_CLIENT_SECRET:''}});assert.equal((await f.req('/api/catalog')).status,200);assert.equal((await f.req('/api/submissions',{method:'POST',body:submission()})).status,401);assert.equal((await f.req('/api/auth/start',{method:'POST',body:{}})).data.error.code,'oauth_not_configured');});
test('OAuth state, browser binding, one-time callback and bridge verifier',async t=>{const f=await fixture(t),flow=await f.begin();assert.equal((await f.callback({...flow,state:'incorrect'})).status,400);assert.equal((await f.callback(flow,'A',{headers:{}})).status,400);const cb=await f.callback(flow);assert.equal(cb.status,200);assert.equal((await f.callback(flow)).status,400);const bridge=JSON.parse(cb.data.match(/postMessage\((\{.*?\}),/)[1]);assert.equal((await f.req('/api/auth/exchange',{method:'POST',body:{...bridge,codeVerifier:'x'.repeat(43)}})).status,400);const good={code:bridge.code,requestId:flow.requestId,codeVerifier:flow.verifier};assert.equal((await f.req('/api/auth/exchange',{method:'POST',body:good})).status,200);assert.equal((await f.req('/api/auth/exchange',{method:'POST',body:good})).status,400);});
test('OAuth state expires and authorization URL cannot be reused',async t=>{const f=await fixture(t),flow=await f.begin();assert.equal((await f.req(`/api/auth/authorize?requestId=${flow.requestId}`,{origin:null})).status,400);f.advance(300001);assert.equal((await f.callback(flow)).status,400);});
test('bridge expires independently and is origin-bound',async t=>{const f=await fixture(t),flow=await f.begin(),cb=await f.callback(flow),bridge=JSON.parse(cb.data.match(/postMessage\((\{.*?\}),/)[1]);assert.equal((await f.req('/api/auth/exchange',{method:'POST',origin:'http://127.0.0.1:8000',body:{...bridge,codeVerifier:flow.verifier}})).status,400);f.advance(60001);assert.equal((await f.req('/api/auth/exchange',{method:'POST',body:{...bridge,codeVerifier:flow.verifier}})).status,400);});
test('successful login contains only public profile and Registry opaque token',async t=>{const f=await fixture(t),login=await f.login();assert.equal(login.profile.displayName,'Development Fixture A');assert.equal(login.token.length,43);assert.equal(login.isAdmin,false);assert.equal(JSON.stringify(login.profile).includes(IDS.A),false);const row=f.store.db.prepare('SELECT * FROM sessions').get();assert.notEqual(row.hash,login.token);assert.equal(row.discord_id,IDS.A);});
test('sessions are bound to original origin, expire, and logout revokes',async t=>{const f=await fixture(t),a=await f.login();assert.equal((await f.req('/api/me',{token:a.token,origin:'http://127.0.0.1:8000'})).status,401);assert.equal((await f.req('/api/auth/logout',{method:'POST',token:a.token,body:{}})).status,200);assert.equal((await f.req('/api/me',{token:a.token})).status,401);const b=await f.login();f.advance(28800001);assert.equal((await f.req('/api/me',{token:b.token})).status,401);});
test('CORS and bearer-session CSRF protection reject missing, evil and null origins',async t=>{const f=await fixture(t),a=await f.login();for(const origin of [null,'https://evil.example','null'])assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission(),origin})).status,403);assert.equal((await f.req('/api/catalog',{origin:'https://evil.example'})).status,403);assert.equal((await f.req('/api/catalog',{origin:ORIGIN})).headers.get('access-control-allow-origin'),ORIGIN);});
test('identity primary key and submission ownership survive profile changes',async t=>{const f=await fixture(t),a=await f.login(),created=await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()});assert.equal(created.status,201);const id=created.data.id;f.profiles.A={...f.profiles.A,displayName:'Changed Display',username:'changed_username',avatarBytes:Buffer.from([137,80,78,71,13,10,26,10])};const again=await f.login();assert.equal(again.profile.displayName,'Changed Display');assert.ok(again.profile.avatarUrl.startsWith('/api/avatars/'));assert.ok(!again.profile.avatarUrl.includes(IDS.A));assert.equal((await f.req(again.profile.avatarUrl)).headers.get('content-type'),'image/png');assert.equal((await f.req('/api/submissions',{token:again.token})).data.items[0].id,id);assert.equal(f.store.db.prepare('SELECT count(*) AS n FROM identities').get().n,1);assert.equal((await f.req('/api/catalog')).data.items[0].submitter.displayName,'Changed Display');});
test('author and submitter distinct; B cannot edit or unlist A submission',async t=>{const f=await fixture(t),a=await f.login(),b=await f.login('B');const created=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({author:'Actual Work Author'})})).data;assert.equal(created.author,'Actual Work Author');assert.equal(created.submitter.displayName,'Development Fixture A');assert.equal((await f.req('/api/submissions',{token:b.token})).data.items.length,0);assert.equal((await f.req(`/api/submissions/${created.id}`,{method:'PATCH',token:b.token,body:{name:'stolen'}})).status,403);assert.equal((await f.req(`/api/submissions/${created.id}/status`,{method:'POST',token:b.token,body:{status:'unlisted'}})).status,403);});
test('owner cannot change owner identity or internal discovery fields',async t=>{const f=await fixture(t),a=await f.login(),created=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;for(const field of ['ownerDiscordUserId','owner_id','github','status','id'])assert.equal((await f.req(`/api/submissions/${created.id}`,{method:'PATCH',token:a.token,body:{[field]:IDS.B}})).status,400);});
test('owner unlisting and relisting retain row and private visibility',async t=>{const f=await fixture(t),a=await f.login(),row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;assert.equal((await f.req('/api/catalog')).data.total,1);await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'unlisted'}});assert.equal((await f.req('/api/catalog')).data.total,0);assert.equal((await f.req(`/api/catalog/${row.id}`)).status,404);assert.equal((await f.req('/api/submissions',{token:a.token})).data.items[0].status,'unlisted');await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'listed'}});assert.equal((await f.req('/api/catalog')).data.total,1);assert.equal(f.store.db.prepare('SELECT count(*) AS n FROM audit').get().n,3);});
test('admin permissions, separate hidden/unlisted moderation, and restore respect owner choice',async t=>{const f=await fixture(t),a=await f.login(),admin=await f.login('ADMIN'),row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;assert.equal(admin.isAdmin,true);assert.equal((await f.req('/api/admin/submissions',{token:a.token})).status,403);const moderate=action=>f.req(`/api/admin/submissions/${row.id}/moderation`,{method:'POST',token:admin.token,body:{action,reason:'Development Fixture moderation'}});await moderate('hide');assert.equal((await f.req('/api/catalog')).data.total,0);let mine=(await f.req('/api/submissions',{token:a.token})).data.items[0];assert.equal(mine.status,'listed');assert.equal(mine.moderation,'hidden');await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'listed'}});assert.equal((await f.req('/api/catalog')).data.total,0);await moderate('restore');assert.equal((await f.req('/api/catalog')).data.total,1);await moderate('unlist');assert.equal((await f.req('/api/submissions',{token:a.token})).data.items[0].moderation,'unlisted');await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'unlisted'}});await moderate('restore');assert.equal((await f.req('/api/catalog')).data.total,0);});
test('admin bans immutable Discord identity, blocks posting/edit/relist and can unban',async t=>{const f=await fixture(t),a=await f.login(),admin=await f.login('ADMIN'),row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;assert.equal((await f.req(`/api/admin/identities/${IDS.A}/ban`,{method:'POST',token:a.token,body:{banned:true}})).status,403);const ban=banned=>f.req(`/api/admin/identities/${IDS.A}/ban`,{method:'POST',token:admin.token,body:{banned,reason:'test'}});await ban(true);assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceUrl:'https://github.com/example/another'})})).status,403);assert.equal((await f.req(`/api/submissions/${row.id}`,{method:'PATCH',token:a.token,body:{name:'change'}})).status,403);f.profiles.A.displayName='New Name';assert.equal((await f.login()).canSubmit,false);assert.equal((await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'unlisted'}})).status,200);assert.equal((await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'listed'}})).status,403);await ban(false);assert.equal((await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'listed'}})).status,200);});
test('GitHub preview needs authentication; source edited to new repo drops old discoveries',async t=>{const f=await fixture(t),a=await f.login();assert.equal((await f.req('/api/github/preview?url=https://github.com/example/fixture')).status,401);assert.equal((await f.req('/api/github/preview?url=https://github.com/example/fixture',{token:a.token})).data.repo,'fixture');const row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;const edited=await f.req(`/api/submissions/${row.id}`,{method:'PATCH',token:a.token,body:{sourceUrl:'https://github.com/example/newrepo'}});assert.equal(edited.data.github.repo,'newrepo');assert.ok(f.inspections.includes('https://github.com/example/newrepo'));assert.equal((await f.req(`/api/submissions/${row.id}`,{method:'PATCH',token:a.token,body:{sourceUrl:'https://github.com/example/missing'}})).status,400);assert.equal((await f.req(`/api/catalog/${row.id}`)).data.github.repo,'newrepo');});
test('Discord sources preserve original post only and cannot be installable packages',async t=>{const f=await fixture(t),a=await f.login(),url='https://discord.com/channels/111111111111111111/222222222222222222/333333333333333333';const row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceType:'discord',sourceUrl:url})})).data;assert.equal(row.sourceUrl,url);assert.equal(row.github,null);assert.equal(row.version,null);for(const sourceUrl of ['https://cdn.discordapp.com/attachments/1/a.json','https://discord.gg/example','https://evil.example/channels/111111111111111111/222222222222222222'])assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceType:'discord',sourceUrl})})).status,400);});
test('source URL validation blocks SSRF, userinfo, alternate hosts and missing repository',async t=>{const f=await fixture(t),a=await f.login();for(const sourceUrl of ['http://github.com/a/b','https://github.com.evil.example/a/b','https://127.0.0.1/a/b','https://user:password@github.com/a/b','https://github.com/a/b?redirect=evil','https://github.com/example/missing']){f.advance(600001);assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceUrl})})).status,400);}assert.equal((await f.req('/api/catalog')).data.total,0);});
test('duplicate source rejected across identities and case variations',async t=>{const f=await fixture(t),a=await f.login(),b=await f.login('B');assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).status,201);assert.equal((await f.req('/api/submissions',{method:'POST',token:b.token,body:submission({sourceUrl:'https://github.com/Example/Fixture/'})})).status,409);});
test('catalog paging/filter/search return only listed visible public DTOs',async t=>{const f=await fixture(t),a=await f.login();for(let i=0;i<3;i++)await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({name:`Fixture ${i}`,sourceUrl:`https://github.com/example/repo${i}`})});await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({name:'Discord Fixture',sourceType:'discord',sourceUrl:'https://discord.com/channels/444444444444444444/555555555555555555'})});const page=(await f.req('/api/catalog?page=1&pageSize=2')).data;assert.equal(page.items.length,2);assert.equal(page.total,4);assert.equal(page.hasMore,true);assert.equal((await f.req('/api/catalog?page=2&pageSize=2')).data.hasMore,false);assert.equal((await f.req('/api/catalog?source=discord')).data.total,1);assert.equal((await f.req('/api/catalog?q=Fixture%201')).data.total,1);const entireCatalog=(await f.req('/api/catalog?pageSize=50')).data;for(const key of [IDS.A,'discord_id','owner_id','banned','username','email','token','moderation'])assert.equal(JSON.stringify(entireCatalog).includes(key),false);assert.equal((await f.req('/api/catalog?pageSize=999')).status,400);});
test('text stays inert JSON, icon uploads/unsafe URLs and long fields rejected',async t=>{const f=await fixture(t),a=await f.login();const row=await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({name:'<script>alert(1)</script>'})});assert.equal(row.status,201);assert.equal(row.data.name,'<script>alert(1)</script>');for(const change of [{name:'x'.repeat(101)},{icon:'data:image/png;base64,AAAA'},{icon:'javascript:alert(1)'},{tags:Array(9).fill('tag')},{icon:'https://127.0.0.1/icon.png'}]){f.advance(600001);assert.equal((await f.req(`/api/submissions/${row.data.id}`,{method:'PATCH',token:a.token,body:change})).status,400);}assert.equal((await f.req(`/api/submissions/${row.data.id}`,{method:'PATCH',token:a.token,body:{description:'x'.repeat(20000)}})).status,413);});
test('per-submitter spam limit does not authorize anonymous user',async t=>{const f=await fixture(t),a=await f.login();for(let i=0;i<5;i++)assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceUrl:`https://github.com/example/repo${i}`})})).status,201);assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceUrl:'https://github.com/example/last'})})).status,429);});
test('SQLite restart preserves identities, ownership, moderation and audit; backup restores',async t=>{const folder=await mkdtemp(join(tmpdir(),'miemie-registry-test-'));t.after(()=>rm(folder,{recursive:true,force:true}));const path=join(folder,'test.sqlite'),f=await fixture(t,{path}),a=await f.login();const row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;const backupPath=join(folder,'backup.sqlite');await f.store.backup(backupPath);const reopened=openStore(path),backup=openStore(backupPath);try{assert.equal(reopened.db.prepare('PRAGMA user_version').get().user_version,1);assert.equal(reopened.db.prepare('SELECT owner_id FROM submissions WHERE id=?').get(row.id).owner_id,IDS.A);assert.equal(backup.db.prepare('SELECT count(*) AS n FROM submissions').get().n,1);assert.equal(backup.db.prepare('SELECT count(*) AS n FROM audit').get().n,1);}finally{reopened.close();backup.close();}});
test('production config requires HTTPS, real random session secret and exact redirect',()=>{assert.throws(()=>loadConfig({NODE_ENV:'production',PUBLIC_BASE_URL:'http://localhost:8787'}));assert.throws(()=>loadConfig({NODE_ENV:'production',PUBLIC_BASE_URL:'https://registry.example',CORS_ORIGINS:'https://tavern.example'}));assert.throws(()=>loadConfig({DISCORD_REDIRECT_URI:'https://evil.example/callback'}));assert.throws(()=>loadConfig({MIEMIE_ADMIN_DISCORD_IDS:'not-an-id'}));assert.throws(()=>loadConfig({CORS_ORIGINS:'*'}));});
test('no OAuth secret/token is bundled into public landing or error responses',async t=>{const f=await fixture(t);for(const path of ['/','/health','/api/catalog','/api/auth/callback?state=bad&code=bad']){const result=await f.req(path);const output=JSON.stringify(result.data);assert.ok(!output.includes(f.config.clientSecret));assert.ok(!output.includes(f.config.sessionSecret));}const env=await readFile(new URL('../.env.example',import.meta.url),'utf8');assert.match(env,/DISCORD_CLIENT_SECRET=\n/);assert.match(env,/SESSION_SECRET=\n/);});
test('ban while asynchronous GitHub validation is pending prevents the write',async t=>{let release,signal;const started=new Promise(resolve=>signal=resolve),gate=new Promise(resolve=>release=resolve);const f=await fixture(t,{beforeInspect:async()=>{signal();await gate;}}),a=await f.login(),admin=await f.login('ADMIN');const pending=f.req('/api/submissions',{method:'POST',token:a.token,body:submission()});await started;await f.req(`/api/admin/identities/${IDS.A}/ban`,{method:'POST',token:admin.token,body:{banned:true}});release();assert.equal((await pending).status,403);assert.equal((await f.req('/api/catalog')).data.total,0);});
test('logout while asynchronous GitHub validation is pending prevents the write',async t=>{let release,signal;const started=new Promise(resolve=>signal=resolve),gate=new Promise(resolve=>release=resolve);const f=await fixture(t,{beforeInspect:async()=>{signal();await gate;}}),a=await f.login();const pending=f.req('/api/submissions',{method:'POST',token:a.token,body:submission()});await started;await f.req('/api/auth/logout',{method:'POST',token:a.token,body:{}});release();assert.equal((await pending).status,401);assert.equal((await f.req('/api/catalog')).data.total,0);});
test('production Registry allows explicitly listed localhost Tavern but never wildcard or remote HTTP',()=>{const config=loadConfig({NODE_ENV:'production',PUBLIC_BASE_URL:'https://registry.example',CORS_ORIGINS:'http://localhost:8000',SESSION_SECRET:'test-only-production-config-secret-xxxxxxxx'});assert.ok(config.allowedOrigins.has('http://localhost:8000'));assert.throws(()=>loadConfig({NODE_ENV:'production',PUBLIC_BASE_URL:'https://registry.example',CORS_ORIGINS:'http://remote.example',SESSION_SECRET:'test-only-production-config-secret-xxxxxxxx'}));});
