import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { createHash } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { loadConfig } from '../src/config.js';
import { openStore } from '../src/store.js';
import { createApp } from '../src/app.js';
const ORIGIN = 'http://localhost:8000';
const IDS = { A:'111111111111111111', B:'222222222222222222', ADMIN:'333333333333333333', OWNER:'999999999999999999' };
const challenge = v => createHash('sha256').update(v).digest('base64url');
const submission = (overrides={}) => ({name:'Development Fixture · Example',description:'Test data, not a real community endorsement.',author:'Fixture Author',sourceType:'github',sourceUrl:'https://github.com/example/fixture',tags:['test'],...overrides});
async function fixture(t, options={}) {
  const config = loadConfig({ DISCORD_CLIENT_ID:'000000000000000001',DISCORD_CLIENT_SECRET:'test-only-discord-secret',SESSION_SECRET:'test-only-session-secret-xxxxxxxxxxxxxxxxxxxxxxxx',MIEMIE_ADMIN_DISCORD_IDS:IDS.ADMIN,MIEMIE_OWNER_DISCORD_ID:IDS.OWNER, ...options.env });
  let clock=Date.now(); const store = openStore(options.path||':memory:');
  const profiles = Object.fromEntries(Object.entries(IDS).map(([key,id])=>[key,{id,displayName:`Development Fixture ${key}`,username:`fixture_${key}`,avatarBytes:null}]));
  const inspections=[], membershipCalls=[];
  const memberships={A:['444444444444444444'], B:[], ADMIN:[], OWNER:[]}; let membershipFailure=false;
  const github = options.github || { async inspect(url) { inspections.push(url); if(options.beforeInspect) await options.beforeInspect(url); const u=new URL(url), [,owner,repo]=u.pathname.split('/'); if(repo==='missing') {const error=new Error('not public'); error.status=400;throw error;} return {owner,repo,compatibility:'external',manifest:null,release:null,reason:'fixture metadata'}; } };
  const app=createApp({config,store,...options.app,now:()=>clock,rateLimit:options.rateLimit||10000,github,discord:{authorizationUrl:state=>`https://discord.com/oauth2/authorize?state=${state}`,async exchange(code){if(!profiles[code])throw new Error('invalid OAuth code');return {profile:profiles[code],credentials:{accessToken:`test-only-discord-access-${code}`,expiresAt:clock+(options.oauthTtlMs||36000000),scopes:['identify','guilds']}};},async listGuilds(token){membershipCalls.push(token);if(options.beforeGuilds)await options.beforeGuilds();if(membershipFailure)throw new Error('private-upstream-details');return [...memberships[token.replace('test-only-discord-access-','')]];}}});
  const server=createServer(app.handler); await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve)); const base=`http://127.0.0.1:${server.address().port}`;
  t.after(async()=>{await new Promise(resolve=>server.close(resolve));app.close();store.close();});
  async function req(path, {method='GET',body,token,origin=ORIGIN,headers={}}={}) {
    const response=await fetch(`${base}${path}`,{method,headers:{...(origin?{Origin:origin}:{}),...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`} : {}),...headers},body:body?JSON.stringify(body):undefined,redirect:'manual'});
    const raw=await response.text();let data;try{data=JSON.parse(raw);}catch{data=raw;} return {status:response.status,data,headers:response.headers};
  }
  async function begin(verifier='v'.repeat(43)) {const start=await req('/api/auth/start',{method:'POST',body:{codeChallenge:challenge(verifier),returnOrigin:ORIGIN}});assert.equal(start.status,200);const auth=await req(new URL(start.data.authorizationUrl).pathname+new URL(start.data.authorizationUrl).search,{origin:null});assert.equal(auth.status,302);return {requestId:start.data.requestId,verifier,cookie:auth.headers.get('set-cookie').split(';')[0],state:new URL(auth.headers.get('location')).searchParams.get('state')};}
  async function callback(flow, who='A', overrides={}) {return req(`/api/auth/callback?state=${encodeURIComponent(flow.state)}&code=${who}`,{origin:null,headers:{Cookie:flow.cookie},...overrides});}
  async function login(who='A') {const flow=await begin();const cb=await callback(flow,who);assert.equal(cb.status,200);const bridge=JSON.parse(cb.data.match(/postMessage\((\{.*?\}),/)[1]);const exchanged=await req('/api/auth/exchange',{method:'POST',body:{code:bridge.code,requestId:flow.requestId,codeVerifier:flow.verifier}});assert.equal(exchanged.status,200);return {...exchanged.data,flow,bridge};}
  return {config,store,req,begin,callback,login,profiles,inspections,memberships,membershipCalls,setMembershipFailure:value=>membershipFailure=value,app,advance:n=>clock+=n};
}

test('public catalog works with no OAuth configuration; unauthenticated posting rejected',async t=>{const f=await fixture(t,{env:{DISCORD_CLIENT_ID:'',DISCORD_CLIENT_SECRET:''}});assert.equal((await f.req('/api/catalog')).status,200);assert.equal((await f.req('/api/submissions',{method:'POST',body:submission()})).status,401);assert.equal((await f.req('/api/auth/start',{method:'POST',body:{}})).data.error.code,'oauth_not_configured');});
test('OAuth state, browser binding, one-time callback and bridge verifier',async t=>{const f=await fixture(t),flow=await f.begin();assert.equal((await f.callback({...flow,state:'incorrect'})).status,400);assert.equal((await f.callback(flow,'A',{headers:{}})).status,400);const cb=await f.callback(flow);assert.equal(cb.status,200);assert.equal((await f.callback(flow)).status,400);const bridge=JSON.parse(cb.data.match(/postMessage\((\{.*?\}),/)[1]);assert.equal((await f.req('/api/auth/exchange',{method:'POST',body:{...bridge,codeVerifier:'x'.repeat(43)}})).status,400);const good={code:bridge.code,requestId:flow.requestId,codeVerifier:flow.verifier};assert.equal((await f.req('/api/auth/exchange',{method:'POST',body:good})).status,200);assert.equal((await f.req('/api/auth/exchange',{method:'POST',body:good})).status,400);});
test('OAuth state expires and authorization URL cannot be reused',async t=>{const f=await fixture(t),flow=await f.begin();assert.equal((await f.req(`/api/auth/authorize?requestId=${flow.requestId}`,{origin:null})).status,400);f.advance(300001);assert.equal((await f.callback(flow)).status,400);});
test('bridge expires independently and is origin-bound',async t=>{const f=await fixture(t),flow=await f.begin(),cb=await f.callback(flow),bridge=JSON.parse(cb.data.match(/postMessage\((\{.*?\}),/)[1]);assert.equal((await f.req('/api/auth/exchange',{method:'POST',origin:'http://127.0.0.1:8000',body:{...bridge,codeVerifier:flow.verifier}})).status,400);f.advance(60001);assert.equal((await f.req('/api/auth/exchange',{method:'POST',body:{...bridge,codeVerifier:flow.verifier}})).status,400);});
test('successful login contains only public profile and Registry opaque token',async t=>{const f=await fixture(t),login=await f.login();assert.equal(login.profile.displayName,'Development Fixture A');assert.equal(login.token.length,43);assert.equal(login.isAdmin,false);assert.equal(JSON.stringify(login.profile).includes(IDS.A),false);const row=f.store.db.prepare('SELECT * FROM sessions').get();assert.notEqual(row.hash,login.token);assert.equal(row.discord_id,IDS.A);});
test('sessions are bound to original origin, expire, and logout revokes',async t=>{const f=await fixture(t),a=await f.login();assert.equal((await f.req('/api/me',{token:a.token,origin:'http://127.0.0.1:8000'})).status,401);assert.equal((await f.req('/api/auth/logout',{method:'POST',token:a.token,body:{}})).status,200);assert.equal((await f.req('/api/me',{token:a.token})).status,401);const b=await f.login();f.advance(28800001);assert.equal((await f.req('/api/me',{token:b.token})).status,401);});
test('CORS and bearer-session CSRF protection reject missing, evil and null origins',async t=>{const f=await fixture(t),a=await f.login();for(const origin of [null,'https://evil.example','null'])assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission(),origin})).status,403);assert.equal((await f.req('/api/catalog',{origin:'https://evil.example'})).status,403);assert.equal((await f.req('/api/catalog',{origin:ORIGIN})).headers.get('access-control-allow-origin'),ORIGIN);});
test('identity primary key and submission ownership survive profile changes',async t=>{const f=await fixture(t),a=await f.login(),created=await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()});assert.equal(created.status,201);const id=created.data.id;f.profiles.A={...f.profiles.A,displayName:'Changed Display',username:'changed_username',avatarBytes:Buffer.from([137,80,78,71,13,10,26,10])};const again=await f.login();assert.equal(again.profile.displayName,'Changed Display');assert.ok(again.profile.avatarUrl.startsWith('/api/avatars/'));assert.ok(!again.profile.avatarUrl.includes(IDS.A));assert.equal((await f.req(again.profile.avatarUrl)).headers.get('content-type'),'image/png');assert.equal((await f.req('/api/submissions',{token:again.token})).data.items[0].id,id);assert.equal(f.store.db.prepare('SELECT count(*) AS n FROM identities').get().n,1);assert.equal((await f.req('/api/catalog')).data.items[0].submitter.displayName,'Changed Display');});
test('author and submitter distinct; B cannot edit or unlist A submission',async t=>{const f=await fixture(t),a=await f.login(),b=await f.login('B');const created=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({author:'Actual Work Author'})})).data;assert.equal(created.author,'Actual Work Author');assert.equal(created.submitter.displayName,'Development Fixture A');assert.equal((await f.req('/api/submissions',{token:b.token})).data.items.length,0);assert.equal((await f.req(`/api/submissions/${created.id}`,{method:'PATCH',token:b.token,body:{name:'stolen'}})).status,404);assert.equal((await f.req(`/api/submissions/${created.id}/status`,{method:'POST',token:b.token,body:{status:'unlisted'}})).status,404);});
test('owner cannot change owner identity or internal discovery fields',async t=>{const f=await fixture(t),a=await f.login(),created=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;for(const field of ['ownerDiscordUserId','owner_id','github','status','id'])assert.equal((await f.req(`/api/submissions/${created.id}`,{method:'PATCH',token:a.token,body:{[field]:IDS.B}})).status,400);});
test('owner unlisting and relisting retain row and private visibility',async t=>{const f=await fixture(t),a=await f.login(),row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;assert.equal((await f.req('/api/catalog')).data.total,1);await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'unlisted'}});assert.equal((await f.req('/api/catalog')).data.total,0);assert.equal((await f.req(`/api/catalog/${row.id}`)).status,404);assert.equal((await f.req('/api/submissions',{token:a.token})).data.items[0].status,'unlisted');await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'listed'}});assert.equal((await f.req('/api/catalog')).data.total,1);assert.equal(f.store.db.prepare("SELECT count(*) AS n FROM audit WHERE actor_id<>'server-bootstrap'").get().n,3);});
test('admin permissions, separate hidden/unlisted moderation, and restore respect owner choice',async t=>{const f=await fixture(t),a=await f.login(),admin=await f.login('ADMIN'),row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;assert.equal(admin.isAdmin,true);assert.equal((await f.req('/api/admin/submissions',{token:a.token})).status,403);const moderate=action=>f.req(`/api/admin/submissions/${row.id}/moderation`,{method:'POST',token:admin.token,body:{action,reason:'Development Fixture moderation'}});await moderate('hide');assert.equal((await f.req('/api/catalog')).data.total,0);let mine=(await f.req('/api/submissions',{token:a.token})).data.items[0];assert.equal(mine.status,'listed');assert.equal(mine.moderation,'hidden');await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'listed'}});assert.equal((await f.req('/api/catalog')).data.total,0);await moderate('restore');assert.equal((await f.req('/api/catalog')).data.total,1);assert.equal((await moderate('unlist')).status,400);await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'unlisted'}});await moderate('restore');assert.equal((await f.req('/api/catalog')).data.total,0);});
test('admin bans immutable Discord identity, blocks posting/edit/relist and can unban',async t=>{const f=await fixture(t),a=await f.login(),admin=await f.login('OWNER'),row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;assert.equal((await f.req(`/api/admin/identities/${IDS.A}/ban`,{method:'POST',token:a.token,body:{banned:true,reason:'test fixture'}})).status,403);const ban=banned=>f.req(`/api/admin/identities/${IDS.A}/ban`,{method:'POST',token:admin.token,body:{banned,reason:'test'}});await ban(true);assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceUrl:'https://github.com/example/another'})})).status,403);assert.equal((await f.req(`/api/submissions/${row.id}`,{method:'PATCH',token:a.token,body:{name:'change'}})).status,403);f.profiles.A.displayName='New Name';assert.equal((await f.login()).canSubmit,false);assert.equal((await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'unlisted'}})).status,403);assert.equal((await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'listed'}})).status,403);await ban(false);assert.equal((await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'listed'}})).status,200);});
test('GitHub preview needs authentication; source edited to new repo drops old discoveries',async t=>{const f=await fixture(t),a=await f.login();assert.equal((await f.req('/api/github/preview?url=https://github.com/example/fixture')).status,401);assert.equal((await f.req('/api/github/preview?url=https://github.com/example/fixture',{token:a.token})).data.repo,'fixture');const row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;const edited=await f.req(`/api/submissions/${row.id}`,{method:'PATCH',token:a.token,body:{sourceUrl:'https://github.com/example/newrepo'}});assert.equal(edited.data.github.repo,'newrepo');assert.ok(f.inspections.includes('https://github.com/example/newrepo'));assert.equal((await f.req(`/api/submissions/${row.id}`,{method:'PATCH',token:a.token,body:{sourceUrl:'https://github.com/example/missing'}})).status,400);assert.equal((await f.req(`/api/catalog/${row.id}`)).data.github.repo,'newrepo');});
test('Discord sources preserve original post only and cannot be installable packages',async t=>{const f=await fixture(t),a=await f.login(),url='https://discord.com/channels/111111111111111111/222222222222222222/333333333333333333';const row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceType:'discord',sourceUrl:url})})).data;assert.equal(row.sourceUrl,url);assert.equal(row.github,null);assert.equal(row.version,null);for(const sourceUrl of ['https://cdn.discordapp.com/attachments/1/a.json','https://discord.gg/example','https://evil.example/channels/111111111111111111/222222222222222222'])assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceType:'discord',sourceUrl})})).status,400);});
test('source URL validation blocks SSRF, userinfo, alternate hosts and missing repository',async t=>{const f=await fixture(t),a=await f.login();for(const sourceUrl of ['http://github.com/a/b','https://github.com.evil.example/a/b','https://127.0.0.1/a/b','https://user:password@github.com/a/b','https://github.com/a/b?redirect=evil','https://github.com/example/missing']){f.advance(600001);assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceUrl})})).status,400);}assert.equal((await f.req('/api/catalog')).data.total,0);});
test('duplicate source rejected only within same owner; other identities cannot probe catalog existence',async t=>{const f=await fixture(t),a=await f.login(),b=await f.login('B');assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).status,201);assert.equal((await f.req('/api/submissions',{method:'POST',token:b.token,body:submission({sourceUrl:'https://github.com/Example/Fixture/'})})).status,201);assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceUrl:'https://github.com/Example/Fixture/'})})).status,409);});
test('catalog paging/filter/search return only listed visible public DTOs',async t=>{const f=await fixture(t),a=await f.login();for(let i=0;i<3;i++)await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({name:`Fixture ${i}`,sourceUrl:`https://github.com/example/repo${i}`})});await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({name:'Discord Fixture',sourceType:'discord',sourceUrl:'https://discord.com/channels/444444444444444444/555555555555555555'})});const page=(await f.req('/api/catalog?page=1&pageSize=2')).data;assert.equal(page.items.length,2);assert.equal(page.total,4);assert.equal(page.hasMore,true);assert.equal((await f.req('/api/catalog?page=2&pageSize=2')).data.hasMore,false);assert.equal((await f.req('/api/catalog?source=discord')).data.total,1);assert.equal((await f.req('/api/catalog?q=Fixture%201')).data.total,1);const entireCatalog=(await f.req('/api/catalog?pageSize=50')).data;for(const key of [IDS.A,'discord_id','owner_id','banned','username','email','token','moderation'])assert.equal(JSON.stringify(entireCatalog).includes(key),false);assert.equal((await f.req('/api/catalog?pageSize=999')).status,400);});
test('text stays inert JSON, icon uploads/unsafe URLs and long fields rejected',async t=>{const f=await fixture(t),a=await f.login();const row=await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({name:'<script>alert(1)</script>'})});assert.equal(row.status,201);assert.equal(row.data.name,'<script>alert(1)</script>');for(const change of [{name:'x'.repeat(101)},{icon:'data:image/png;base64,AAAA'},{icon:'javascript:alert(1)'},{tags:Array(9).fill('tag')},{icon:'https://127.0.0.1/icon.png'}]){f.advance(600001);assert.equal((await f.req(`/api/submissions/${row.data.id}`,{method:'PATCH',token:a.token,body:change})).status,400);}assert.equal((await f.req(`/api/submissions/${row.data.id}`,{method:'PATCH',token:a.token,body:{description:'x'.repeat(20000)}})).status,413);});
test('per-submitter spam limit does not authorize anonymous user',async t=>{const f=await fixture(t),a=await f.login();for(let i=0;i<5;i++)assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceUrl:`https://github.com/example/repo${i}`})})).status,201);assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceUrl:'https://github.com/example/last'})})).status,429);});
test('SQLite restart preserves identities, ownership, moderation and audit; backup restores',async t=>{const folder=await mkdtemp(join(tmpdir(),'miemie-registry-test-'));t.after(()=>rm(folder,{recursive:true,force:true}));const path=join(folder,'test.sqlite'),f=await fixture(t,{path}),a=await f.login();const row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;const backupPath=join(folder,'backup.sqlite');await f.store.backup(backupPath);const reopened=openStore(path),backup=openStore(backupPath);try{assert.equal(reopened.db.prepare('PRAGMA user_version').get().user_version,3);assert.equal(reopened.db.prepare('SELECT owner_id FROM submissions WHERE id=?').get(row.id).owner_id,IDS.A);assert.equal(backup.db.prepare('SELECT count(*) AS n FROM submissions').get().n,1);assert.equal(backup.db.prepare("SELECT count(*) AS n FROM audit WHERE actor_id<>'server-bootstrap'").get().n,1);}finally{reopened.close();backup.close();}});
test('production config requires HTTPS, real random session secret and exact redirect',()=>{assert.throws(()=>loadConfig({NODE_ENV:'production',PUBLIC_BASE_URL:'http://localhost:8787'}));assert.throws(()=>loadConfig({NODE_ENV:'production',PUBLIC_BASE_URL:'https://registry.example',CORS_ORIGINS:'https://tavern.example'}));assert.throws(()=>loadConfig({DISCORD_REDIRECT_URI:'https://evil.example/callback'}));assert.throws(()=>loadConfig({MIEMIE_ADMIN_DISCORD_IDS:'not-an-id'}));assert.throws(()=>loadConfig({CORS_ORIGINS:'*'}));});
test('no OAuth secret/token is bundled into public landing or error responses',async t=>{const f=await fixture(t);for(const path of ['/','/health','/api/catalog','/api/auth/callback?state=bad&code=bad']){const result=await f.req(path);const output=JSON.stringify(result.data);assert.ok(!output.includes(f.config.clientSecret));assert.ok(!output.includes(f.config.sessionSecret));}const env=await readFile(new URL('../.env.example',import.meta.url),'utf8');assert.match(env,/DISCORD_CLIENT_SECRET=\n/);assert.match(env,/SESSION_SECRET=\n/);});
test('ban while asynchronous GitHub validation is pending prevents the write',async t=>{let release,signal;const started=new Promise(resolve=>signal=resolve),gate=new Promise(resolve=>release=resolve);const f=await fixture(t,{beforeInspect:async()=>{signal();await gate;}}),a=await f.login(),admin=await f.login('OWNER');const pending=f.req('/api/submissions',{method:'POST',token:a.token,body:submission()});await started;await f.req(`/api/admin/identities/${IDS.A}/ban`,{method:'POST',token:admin.token,body:{banned:true,reason:'test fixture'}});release();assert.equal((await pending).status,403);assert.equal((await f.req('/api/catalog')).data.total,0);});
test('logout while asynchronous GitHub validation is pending prevents the write',async t=>{let release,signal;const started=new Promise(resolve=>signal=resolve),gate=new Promise(resolve=>release=resolve);const f=await fixture(t,{beforeInspect:async()=>{signal();await gate;}}),a=await f.login();const pending=f.req('/api/submissions',{method:'POST',token:a.token,body:submission()});await started;await f.req('/api/auth/logout',{method:'POST',token:a.token,body:{}});release();assert.equal((await pending).status,401);assert.equal((await f.req('/api/catalog')).data.total,0);});
test('production Registry allows explicitly listed localhost Tavern but never wildcard or remote HTTP',()=>{const env={NODE_ENV:'production',PUBLIC_BASE_URL:'https://registry.miemie-fixture.org',CORS_ORIGINS:'http://localhost:8000',SESSION_SECRET:'test-only-production-config-secret-xxxxxxxx',DISCORD_CLIENT_ID:'000000000000000001',DISCORD_CLIENT_SECRET:'development-fixture-not-a-real-secret'};const config=loadConfig(env);assert.ok(config.allowedOrigins.has('http://localhost:8000'));for(const origin of ['*','http://remote.example'])assert.throws(()=>loadConfig({...env,CORS_ORIGINS:origin}));});

const GUILD='444444444444444444', OTHER_GUILD='777777777777777777';
const post=(guild=GUILD,suffix='666666666666666666')=>`https://discord.com/channels/${guild}/555555555555555555/${suffix}`;
const restricted=(changes={})=>submission({name:'Private Development Fixture',sourceType:'discord',sourceUrl:post(),visibility:'discord_guild',...changes});

test('Catalog remains empty after GitHub preview; only a deliberate submission lists a project',async t=>{const f=await fixture(t),a=await f.login();assert.equal((await f.req('/api/github/preview?url=https://github.com/SheepSheepLab/MieMie-Polisher',{token:a.token})).status,200);assert.equal((await f.req('/api/catalog')).data.total,0);assert.equal(f.store.db.prepare('SELECT count(*) AS n FROM submissions').get().n,0);});
test('Guild ACL filters anonymous/nonmember list, search, count, detail, and forged query parameters',async t=>{
  const f=await fixture(t),a=await f.login(),b=await f.login('B');
  const saved=await f.req('/api/submissions',{method:'POST',token:a.token,body:restricted()});assert.equal(saved.status,201);
  await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()});
  for(const token of [undefined,b.token]){
    const catalog=await f.req(`/api/catalog?pageSize=1&guildIds=${GUILD}&visibilityGuildId=${GUILD}`,{token});assert.equal(catalog.data.total,1);assert.equal(catalog.data.hasMore,false);assert.equal(catalog.data.items.length,1);assert.equal(catalog.data.items[0].visibility,'public');
    assert.equal((await f.req('/api/catalog?q=Private',{token})).data.total,0);
    assert.deepEqual((await f.req(`/api/catalog/${saved.data.id}`,{token})).data,(await f.req('/api/catalog/absent',{token})).data);
  }
  const permitted=(await f.req('/api/catalog?pageSize=1',{token:a.token})).data;assert.equal(permitted.total,2);assert.equal(permitted.hasMore,true);
  const detail=(await f.req(`/api/catalog/${saved.data.id}`,{token:a.token})).data;assert.equal(detail.name,'Private Development Fixture');assert.equal(detail.visibility,'discord_guild');
  for(const field of ['visibilityGuildId','visibilitySourceUrl','ownerDiscordUserId','discord_id','credentials','accessToken','guildIds'])assert.equal(field in detail,false);
  const row=f.store.getEntry(saved.data.id);assert.equal(row.visibility_guild_id,GUILD);assert.equal(JSON.parse(row.discord_json).channelId,'555555555555555555');assert.equal(JSON.parse(row.discord_json).messageId,'666666666666666666');
});
test('membership is revalidated for every Catalog request; leaving guild revokes access immediately',async t=>{const f=await fixture(t),a=await f.login(),row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:restricted()})).data;assert.equal((await f.req(`/api/catalog/${row.id}`,{token:a.token})).status,200);f.memberships.A=[];assert.equal((await f.req(`/api/catalog/${row.id}`,{token:a.token})).status,404);assert.equal((await f.req('/api/catalog',{token:a.token})).data.total,0);assert.ok(f.membershipCalls.length>=4);});
test('Discord membership failure fails closed without leaking upstream body or cached private rows',async t=>{const f=await fixture(t),a=await f.login(),row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:restricted()})).data;await f.req('/api/catalog',{token:a.token});f.setMembershipFailure(true);for(const path of ['/api/catalog',`/api/catalog/${row.id}`]){const result=await f.req(path,{token:a.token});assert.equal(result.status,503);assert.equal(result.data.error.code,'membership_unavailable');assert.ok(!JSON.stringify(result.data).includes('private-upstream-details'));assert.ok(!JSON.stringify(result.data).includes(row.name));}assert.equal((await f.req('/api/catalog')).data.total,0);});
test('create rejects nonmember restriction and client-supplied guild/ownership identifiers',async t=>{const f=await fixture(t),b=await f.login('B');assert.equal((await f.req('/api/submissions',{method:'POST',token:b.token,body:restricted()})).status,403);for(const field of ['visibilityGuildId','guildIds','guildId','ownerDiscordUserId']){assert.equal((await f.req('/api/submissions',{method:'POST',token:b.token,body:restricted({[field]:GUILD})})).status,400);}assert.equal((await f.req('/api/catalog')).data.total,0);});
test('default visibility is public and public creation does not require membership lookup',async t=>{const f=await fixture(t),b=await f.login('B');f.setMembershipFailure(true);const result=await f.req('/api/submissions',{method:'POST',token:b.token,body:restricted({visibility:undefined})});assert.equal(result.status,201);assert.equal(result.data.visibility,'public');assert.equal(f.membershipCalls.length,0);assert.equal((await f.req('/api/catalog')).data.total,1);});
test('GitHub projects support same Guild ACL using verified Discord community link without changing repository ownership',async t=>{const f=await fixture(t),a=await f.login(),saved=await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({visibility:'discord_guild',visibilitySourceUrl:post()})});assert.equal(saved.status,201);assert.equal(saved.data.sourceType,'github');assert.equal(saved.data.visibilitySourceUrl,post());assert.equal((await f.req('/api/catalog')).data.total,0);assert.equal((await f.req('/api/catalog',{token:a.token})).data.total,1);assert.equal((await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({sourceUrl:'https://github.com/example/other',visibility:'discord_guild',visibilitySourceUrl:'https://discord.gg/invite'})})).status,400);});
test('editing Discord source or public visibility must revalidate new Guild and discard previous anchor',async t=>{const f=await fixture(t),a=await f.login(),saved=(await f.req('/api/submissions',{method:'POST',token:a.token,body:restricted()})).data;const edit=body=>f.req(`/api/submissions/${saved.id}`,{method:'PATCH',token:a.token,body});assert.equal((await edit({sourceUrl:post(OTHER_GUILD)})).status,403);assert.equal(f.store.getEntry(saved.id).visibility_guild_id,GUILD);f.memberships.A=[OTHER_GUILD];assert.equal((await edit({sourceUrl:post(OTHER_GUILD)})).status,200);assert.equal(f.store.getEntry(saved.id).visibility_guild_id,OTHER_GUILD);assert.equal((await edit({visibility:'public'})).status,200);assert.equal(f.store.getEntry(saved.id).visibility_guild_id,null);f.memberships.A=[];assert.equal((await edit({visibility:'discord_guild'})).status,403);assert.equal(f.store.getEntry(saved.id).visibility,'public');});
test('Github repository change clears old discovery and forces revalidation even when other source was previewed',async t=>{const f=await fixture(t),a=await f.login(),saved=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;await f.req('/api/github/preview?url=https://github.com/example/second',{token:a.token});const before=f.inspections.length;const changed=await f.req(`/api/submissions/${saved.id}`,{method:'PATCH',token:a.token,body:{sourceUrl:'https://github.com/example/second'}});assert.equal(changed.status,200);assert.equal(f.inspections.length,before+1);assert.equal(changed.data.github.repo,'second');});
test('Guild display/profile changes never change immutable restriction or submission owner',async t=>{const f=await fixture(t),a=await f.login(),saved=(await f.req('/api/submissions',{method:'POST',token:a.token,body:restricted()})).data;f.profiles.A.displayName='New name after guild rename';f.profiles.A.username='new_username';const again=await f.login();const own=(await f.req('/api/submissions',{token:again.token})).data.items[0];assert.equal(own.id,saved.id);assert.equal(own.submitter.displayName,f.profiles.A.displayName);assert.equal(f.store.getEntry(saved.id).visibility_guild_id,GUILD);assert.equal((await f.req('/api/catalog',{token:again.token})).data.total,1);});
test('relisting restricted entries requires current membership; unlisting preserves record',async t=>{const f=await fixture(t),a=await f.login(),saved=(await f.req('/api/submissions',{method:'POST',token:a.token,body:restricted()})).data;const status=value=>f.req(`/api/submissions/${saved.id}/status`,{method:'POST',token:a.token,body:{status:value}});assert.equal((await status('unlisted')).status,200);f.memberships.A=[];assert.equal((await status('listed')).status,403);assert.equal((await f.req('/api/submissions',{token:a.token})).data.items[0].status,'unlisted');f.memberships.A=[GUILD];assert.equal((await status('listed')).status,200);assert.equal((await f.req('/api/catalog',{token:a.token})).data.total,1);});
test('private rows cannot be discovered via submission/edit ID or source duplication',async t=>{const f=await fixture(t),a=await f.login(),b=await f.login('B'),saved=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission({visibility:'discord_guild',visibilitySourceUrl:post()})})).data;assert.equal((await f.req('/api/catalog',{token:b.token})).data.total,0);const probes=[];for(const path of [`/api/submissions/${saved.id}`,'/api/submissions/absent']){const result=await f.req(path,{method:'PATCH',token:b.token,body:{description:'probe'}});assert.equal(result.status,404);probes.push(result.data);}assert.deepEqual(probes[0],probes[1]);const own=await f.req('/api/submissions',{method:'POST',token:b.token,body:submission()});assert.equal(own.status,201);assert.notEqual(own.data.id,saved.id);assert.equal((await f.req('/api/submissions',{token:b.token})).data.items.length,1);});
test('ban prevents all owner mutations while history remains available to administrators',async t=>{const f=await fixture(t),a=await f.login(),admin=await f.login('OWNER'),row=(await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()})).data;await f.req(`/api/admin/identities/${IDS.A}/ban`,{method:'POST',token:admin.token,body:{banned:true,reason:'test fixture'}});assert.equal((await f.req(`/api/submissions/${row.id}/status`,{method:'POST',token:a.token,body:{status:'unlisted'}})).status,403);assert.equal((await f.req(`/api/submissions/${row.id}`,{method:'PATCH',token:a.token,body:{name:'changed'}})).status,403);assert.equal((await f.req('/api/admin/submissions',{token:admin.token})).data.items[0].submitterBanned,true);assert.equal((await f.req('/api/catalog')).data.total,1);});
test('OAuth credentials never reach storage, public DTOs, callbacks, or profile responses; expiry forces login',async t=>{const f=await fixture(t,{oauthTtlMs:1000}),a=await f.login();await f.req('/api/submissions',{method:'POST',token:a.token,body:restricted()});for(const table of ['identities','sessions','submissions','audit'])assert.ok(!JSON.stringify(f.store.db.prepare(`SELECT * FROM ${table}`).all()).includes('test-only-discord-access'));for(const path of ['/api/me','/api/catalog','/api/submissions'])assert.ok(!JSON.stringify((await f.req(path,{token:a.token})).data).includes('test-only-discord-access'));f.advance(1001);assert.equal((await f.req('/api/catalog',{token:a.token})).status,401);assert.equal((await f.req('/api/catalog')).data.total,0);});
test('persisted Registry session cannot authenticate after process restart loses OAuth credentials',async t=>{const folder=await mkdtemp(join(tmpdir(),'miemie-acl-restart-'));t.after(()=>rm(folder,{recursive:true,force:true}));const path=join(folder,'test.sqlite'),f=await fixture(t,{path}),a=await f.login();await f.req('/api/submissions',{method:'POST',token:a.token,body:restricted()});const restarted=await fixture(t,{path});assert.equal((await restarted.req('/api/me',{token:a.token})).status,401);assert.equal((await restarted.req('/api/catalog',{token:a.token})).status,401);assert.equal((await restarted.req('/api/catalog')).data.total,0);const renewed=await restarted.login();assert.equal((await restarted.req('/api/submissions',{token:renewed.token})).data.items.length,1);});
test('logout during member lookup prevents protected Catalog response and restricted write',async t=>{let release,started;const gate=new Promise(resolve=>release=resolve),start=new Promise(resolve=>started=resolve);const f=await fixture(t,{beforeGuilds:async()=>{started();await gate;}}),a=await f.login();const pending=f.req('/api/submissions',{method:'POST',token:a.token,body:restricted()});await start;await f.req('/api/auth/logout',{method:'POST',token:a.token,body:{}});release();assert.equal((await pending).status,401);assert.equal((await f.req('/api/catalog')).data.total,0);});
test('v1 SQLite migration preserves all data and changes duplicate scope without creating Catalog fixtures',async t=>{
  const folder=await mkdtemp(join(tmpdir(),'miemie-v1-migration-'));t.after(()=>rm(folder,{recursive:true,force:true}));const path=join(folder,'v1.sqlite');const db=new DatabaseSync(path);
  db.exec(`CREATE TABLE identities(discord_id TEXT PRIMARY KEY,display_name TEXT NOT NULL,username TEXT NOT NULL,avatar_key TEXT,profile_updated_at INTEGER NOT NULL,banned INTEGER NOT NULL DEFAULT 0);
  CREATE TABLE avatars(key TEXT PRIMARY KEY,bytes BLOB NOT NULL,mime TEXT NOT NULL);
  CREATE TABLE sessions(hash TEXT PRIMARY KEY,discord_id TEXT NOT NULL REFERENCES identities(discord_id),origin TEXT NOT NULL,expires_at INTEGER NOT NULL);
  CREATE TABLE submissions(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES identities(discord_id),name TEXT NOT NULL,description TEXT NOT NULL,author TEXT NOT NULL,source_type TEXT NOT NULL,source_url TEXT NOT NULL,icon TEXT,tags_json TEXT NOT NULL,github_json TEXT,owner_status TEXT NOT NULL DEFAULT 'listed',moderation TEXT NOT NULL DEFAULT 'visible',moderation_reason TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(source_url));
  CREATE TABLE audit(id INTEGER PRIMARY KEY,actor_id TEXT NOT NULL,action TEXT NOT NULL,target_id TEXT NOT NULL,reason TEXT NOT NULL,created_at INTEGER NOT NULL);
  CREATE INDEX submissions_owner ON submissions(owner_id); CREATE INDEX sessions_expiry ON sessions(expires_at); PRAGMA user_version=1;`);
  db.prepare('INSERT INTO identities VALUES(?,?,?,?,?,?)').run(IDS.A,'Legacy Name','legacy_name',null,100,1);
  db.prepare('INSERT INTO submissions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('legacy',IDS.A,'Old Project','Kept Description','Author','github','https://github.com/example/legacy',null,'["legacy"]','{"manifest":null}','unlisted','hidden','Legacy moderation',100,200);
  db.prepare('INSERT INTO audit VALUES(?,?,?,?,?,?)').run(1,IDS.A,'create','legacy','reason',100);
  const original=db.prepare('SELECT * FROM submissions').get();db.close();const migrated=openStore(path);try{assert.equal(migrated.db.prepare('PRAGMA user_version').get().user_version,3);const row=migrated.getEntry('legacy');for(const[key,value]of Object.entries(original))assert.equal(row[key],value);assert.equal(row.visibility,'public');assert.equal(migrated.getIdentity(IDS.A).banned,1);assert.equal(migrated.db.prepare("SELECT count(*) AS n FROM audit WHERE actor_id<>'server-bootstrap'").get().n,1);assert.equal(migrated.listCatalog({page:1,pageSize:20}).total,0);migrated.upsertIdentity({id:IDS.B,displayName:'B',username:'b',avatarBytes:null},300);const input={...submission({sourceUrl:original.source_url}),icon:null};migrated.insertSubmission({id:'other-owner',ownerId:IDS.B,input,github:null,time:300});assert.equal(migrated.countOwn(IDS.B),1);}finally{migrated.close();}
});

test('PKCE handoff completes without opener, messages, or third-party cookies and confirms current user',async t=>{
 const f=await fixture(t),flow=await f.begin();
 const complete=(overrides={})=>f.req('/api/auth/complete',{method:'POST',body:{requestId:flow.requestId,codeVerifier:flow.verifier},...overrides});
 const pending=await complete();assert.equal(pending.status,202);assert.deepEqual(pending.data,{status:'pending'});
 assert.equal((await complete({origin:'http://127.0.0.1:8000'})).status,400);
 assert.equal((await complete({body:{requestId:flow.requestId,codeVerifier:'x'.repeat(43)}})).status,400);
 assert.equal((await complete({body:{requestId:'z'.repeat(43),codeVerifier:flow.verifier}})).status,400);
 const callback=await f.callback(flow);assert.equal(callback.status,200);
 const result=await complete();assert.equal(result.status,200);assert.equal(result.data.profile.displayName,'Development Fixture A');
 assert.doesNotMatch(JSON.stringify(result.data),new RegExp(IDS.A+'|test-only-discord-access'));
 assert.equal((await f.req('/api/me',{token:result.data.token})).status,200);
 assert.equal((await complete()).status,400);
 const bridge=JSON.parse(callback.data.match(/postMessage\((\{.*?\}),/)[1]);
 assert.equal((await f.req('/api/auth/exchange',{method:'POST',body:{...bridge,codeVerifier:flow.verifier}})).status,400);
});
test('legacy exchange consumes polling handoff too; concurrent completions create exactly one session',async t=>{
 const f=await fixture(t),old=await f.login();
 assert.equal((await f.req('/api/auth/complete',{method:'POST',body:{requestId:old.flow.requestId,codeVerifier:old.flow.verifier}})).status,400);
 const flow=await f.begin();await f.callback(flow);
 const results=await Promise.all([1,2].map(()=>f.req('/api/auth/complete',{method:'POST',body:{requestId:flow.requestId,codeVerifier:flow.verifier}})));
 assert.deepEqual(results.map(x=>x.status).sort(),[200,400]);assert.equal(f.store.db.prepare('SELECT count(*) AS n FROM sessions').get().n,2);
});
test('handoff deadlines, callback failure, missing Origin, and credential-free CORS fail safely',async t=>{
 const f=await fixture(t),flow=await f.begin();
 const body={requestId:flow.requestId,codeVerifier:flow.verifier};
 assert.equal((await f.req('/api/auth/complete',{method:'POST',origin:null,body})).status,403);
 const preflight=await f.req('/api/auth/complete',{method:'OPTIONS'});assert.equal(preflight.status,204);
 assert.equal(preflight.headers.get('access-control-allow-credentials'),null);assert.match(preflight.headers.get('access-control-allow-headers'),/Authorization/);
 f.advance(300001);assert.equal((await f.req('/api/auth/complete',{method:'POST',body})).status,400);
 const another=await f.begin();await f.callback(another);f.advance(60001);
 assert.equal((await f.req('/api/auth/complete',{method:'POST',body:{requestId:another.requestId,codeVerifier:another.verifier}})).status,400);
});

test('active GitHub submission refreshes Release cache after TTL without resubmission; ACL and owner untouched',async t=>{
 let version='1.1.0', calls=0, fail=false;
 const f=await fixture(t,{app:{catalogRefreshTtlMs:60000},github:{async inspect(){calls++;if(fail)throw Error('upstream unavailable');return {compatibility:'installable',manifest:{id:'fixture.polisher',version},release:{version,tag:'v'+version}};}}});
 const a=await f.login('A');const made=await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()});assert.equal(made.status,201);const id=made.data.id;
 assert.equal((await f.req('/api/catalog')).data.items[0].version,'1.1.0');const before=f.store.getEntry(id);
 version='1.1.1';f.advance(60001);
 const newer=await f.req('/api/catalog');assert.equal(newer.data.items[0].version,'1.1.1');assert.equal(newer.data.total,1);
 const after=f.store.getEntry(id);for(const key of Object.keys(before).filter(k=>k!=='github_json'))assert.deepEqual(after[key],before[key]);
 const count=calls;await f.req('/api/catalog/'+id);assert.equal(calls,count);
 fail=true;f.advance(60001);assert.equal((await f.req('/api/catalog')).data.items[0].version,'1.1.1');
 await f.req('/api/submissions/'+id+'/status',{method:'POST',token:a.token,body:{status:'unlisted'}});f.advance(60001);const last=calls;
 assert.equal((await f.req('/api/catalog')).data.total,0);assert.equal((await f.req('/api/catalog/'+id)).status,404);assert.equal(calls,last);
});
test('late GitHub cache write cannot overwrite a source edit',async t=>{
 const f=await fixture(t),a=await f.login('A');const made=await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()});const before=f.store.getEntry(made.data.id);
 await f.req('/api/submissions/'+made.data.id,{method:'PATCH',token:a.token,body:{sourceUrl:'https://github.com/example/new-repo'}});
 f.store.refreshGithub(before,{release:{version:'99.0.0'}});assert.notEqual(JSON.parse(f.store.getEntry(made.data.id).github_json).release?.version,'99.0.0');
});

test('automatic Catalog refresh has a global budget and invalid releases retain last validated cache',async t=>{
 let calls=0,invalid=false;
 const f=await fixture(t,{app:{catalogRefreshBudget:1,catalogRefreshTtlMs:60000},github:{async inspect(){calls++;return invalid?{compatibility:'external',manifest:null,release:{version:'2.0.0'}}:{compatibility:'installable',manifest:{id:'fixture.package',version:'1.1.0'},release:{version:'1.1.0'}};}}});
 const a=await f.login('A');await f.req('/api/submissions',{method:'POST',token:a.token,body:submission()});
 await f.req('/api/catalog');assert.equal(calls,1);invalid=true;f.advance(60001);
 assert.equal((await f.req('/api/catalog')).data.items[0].version,'1.1.0');assert.equal(calls,1);
 f.advance(3600000);assert.equal((await f.req('/api/catalog')).data.items[0].version,'1.1.0');assert.equal(calls,2);
});
